spring:
  datasource:
    url : jdbc:postgresql://tiny.db.elephantsql.com:5432/bcljfkzu
    username : bcljfkzu
    password :
    hikari :
      schema : public
  jpa :
    databasePlatform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : none
    properties :
      hibernate :
        show_sql : true