spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/testing
    username :
    password :
    hikari :
      schema : myschema
  jpa :
    databasePlatform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : none
    properties :
      hibernate :
        show_sql : true

security:
  firebase-props:
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: localhost
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${CORS_DOMAIN}
    - http://localhost:3000
    - http://localhost:8081
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
    - device-id
    - login-type
  allowed-public-apis:
    - /auth/v1/init
    - /user/v1/search
    - /test/**
  exposed-headers:
    - X-Xsrf-Token