spring:
  datasource:
    url : jdbc:postgresql://tiny.db.elephantsql.com:5432/bcljfkzu
    username : bcljfkzu
    password :
    hikari :
      schema : public
  jpa :
    databasePlatform : org.hibernate.dialect.PostgreSQLDialect
    hibernate :
      ddl-auto : none
    properties :
      hibernate :
        show_sql : false

firebase :
  type : service_account
  project-id : test-fcm-token
  private-key-id : 682a16a60ce954d5908c01afc101698a6a8b6391
  client-email : firebase-adminsdk-437ho@test-fcm-token.iam.gserviceaccount.com
  client-id : 102810167527662111640
  auth-uri : https://accounts.google.com/o/oauth2/auth
  token-uri : https://oauth2.googleapis.com/token
  auth-provider-x509-cert-url : https://www.googleapis.com/oauth2/v1/certs
  client-x509-cert-url : https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-437ho%40test-fcm-token.iam.gserviceaccount.com

security:
  firebase-props:
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: localhost
    path: /
  allow-credentials: true
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8081
    - https://test-fcm-token.firebaseapp.com/
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
    - device-id
    - login-type
  allowed-public-apis:
    - /auth/v1/init
    - /user/v1/search
  exposed-headers:
    - X-Xsrf-Token